version: '3.8'

services:
  webapp:
    build: ./apache
    container_name: webapp
    expose:
      - "80"
    networks:
      - webnet

  haproxy:
    build: ./haproxy
    container_name: haproxy
    ports:
      - "443:443"
    depends_on:
      - webapp
    networks:
      - webnet

networks:
  webnet: